### ISSUE TITLE
Vuex state management

### ISSUE THREAD

**Issue by vaggelis2018** [anthonygore/vue-js-laravel-multi-ssr#1]
Hello and nice guide but i have a problem with vuex and state management. This guide renders only the markup without data from a database or an ajax (axios) call. For example if i get my products from an api call nothing from the products will be rendered in the server.

**Comment by anthonygore** [comment]
Yeah I'm pretty sure you can't pre-fetch data with Vue running in V8Js. The problem is that the XmlHttpRequest API is not defined in the environment so you can't do AJAX calls.

**Comment by vaggelis2018** [comment]
Yeap this is the error i get every time i try to get.

**Comment by anthonygore** [comment]
I think you'll have to find a workaround. My suggestion would be to deal with the pre-fetching in Laravel and use the results as initial state in Vuex.

Keep me updated if you find a good solution.

**Comment by vaggelis2018** [comment]
Already tried this solution but it needs double code to pass data in the correct form to vue because every time i do this vue gets an empty variable for a weird reason

**Comment by neverthemachineforever** [comment]
@vaggelis2018, did you ever find out why using Vuex this way resulted in an undefined variable? I'm running into the same issue I believe. Whenever I try and do anything with the Vuex store in my server entry, my app renders to undefined without error. Thanks!

**Comment by anthonygore** [comment]
If someone can provide a repo with an example of this problem I'd be happy to help debug

**Comment by neverthemachineforever** [comment]
Just FYI, this turned out to be an error of mine in how I was setting the state and not related to SSR. Thanks for the help though!
