### ISSUE TITLE
Style Tags Are Breaking SSR

### ISSUE THREAD

**Issue by pet1330** [anthonygore/vue-js-laravel-multi-ssr#3]
Hi, 

I was reading the related article, it has really helped! I've managed to get a project working, but am having an issue with the style tags not working.

Whenever you add a `<style>` section to a Vue component that you are trying to **SSR**, the `render` function in `AppController` returns `undefined`. Using your repository, I added empty style tags
```html
<style>
</style>
```
to the bottom of your `resource/assets/js/components/App.vue` file and now it will only return `undefined`.

Do you have any idea why this might be happening or how to fix it?

**Comment by anthonygore** [comment]
Have you looked into the Laravel Mix docs? If the render function is returning undefined my guess is that there was a problem in the webpack build phase

**Comment by KitaXvost** [comment]
I have the same problem

I connect the **webpack.config.js** file to the root of the laravel project from the SSR-manual:
```
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const isProduction = process.env.NODE_ENV === 'production'
module.exports = {
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {

          extractCSS: isProduction
        }
      },
         ]
  },
  plugins: isProduction

    ? [new ExtractTextPlugin({ filename: 'common.[chunkhash].css' })]
    : []
}
```
but there is no result
